name: Generate documentation

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    name: Generate documentation and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate documentation
        run: cargo doc --no-deps

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc/trust
